import type { SiteConfig } from './types'

/**
 * Aura's Digital Dream — editorial scroll archive.
 * Renaissance × ephemeral × futuristic.
 */
export const siteConfig: SiteConfig = {
  locale: 'ro',
  siteTitle: "Aura's Digital Dream | Marketing · Design · Web",
  siteDescription:
    'Designer, marketer și sculptor digital. Identități care unesc Renașterea, efemerul și viitorul — strategie, design și experiențe digitale.',
  theme: {
    paper: '#f3ecdf',
    paperDeep: '#e7dcc8',
    ink: '#2a1e22',
    mutedInk: '#65534f',
    rule: '#c4b08d',
    accent: '#7d1f3c',
    mineral: '#4e7d84',
  },
  brand: {
    name: "Aura's Digital Dream",
    logoSrc: '/editorial-media/aura-digital-dream-logo.svg',
    subtitle: "Digital Dream · Marketing · Design · Web",
    edition: 'EDIȚIA MMXXVI · RENAISSANCE DIGITAL',
    sealCharacter: 'A',
  },
  navigation: [
    { id: 'cover', index: 'I', label: 'Deschidere' },
    { id: 'chapters', index: 'II', label: 'Manifest' },
    { id: 'landscape', index: 'III', label: 'Atlas' },
    { id: 'specimen', index: 'IV', label: 'Sistem' },
    { id: 'records', index: 'V', label: 'Servicii' },
    { id: 'colophon', index: 'VI', label: 'Colofon' },
  ],
  hero: {
    kicker: 'MARKETING · DESIGN · WEB',
    title: "Aura's Digital Dream",
    statement:
      'Așa cum sculptorul vede forma în piatră înainte ca lumea s-o vadă — modelez identități care unesc strategia, estetica și tehnologia. Unde Renașterea întâlnește viitorul, brandul tău devine memorabil.',
    scrollLabel: 'Derulează spre vis',
    image: {
      src: '/editorial-media/hero-aura.png',
      alt: 'Portret editorial de profil al unei femei cu ochelari futuriști chihlimbar, într-o grădină renascentistă cu statui de marmură, trandafiri și bule plutitoare',
      position: '42% 46%',
    },
  },
  chapters: [
    {
      id: 'strategie',
      index: 'I',
      label: 'Strategie',
      script: 'VEDERE',
      title: 'Strategia vede forma înainte ca lumea s-o vadă',
      summary:
        'Nimic nu se întâmplă la întâmplare: direcția vizuală, structura și mesajele-cheie se decid înainte ca primul pixel să existe.',
      coordinates: 'Scena 01 · Apariția',
      image: { src: '/editorial-media/chapter-strategie-soldiers.png', alt: 'Gardă de războinici în armură aurie, mozaic în stil Klimt, printre flori aurii', position: '50% 35%' },
      detail: {
        kicker: 'Capitolul I · Strategie',
        title: 'Te ajut să apari.',
        intro: 'Strategia și poziționarea scot brandul din anonimat și îl așază exact în lumina potrivită.',
        quote: 'Claritatea nu se improvizează. Se construiește — din obiectiv, public și adevăr.',
        quoteAttribution: 'Caiet de strategie · Aura',
        paragraphs: [
          'Înainte de orice culoare sau font, ascult. Obiectivele tale, publicul tău, provocările brandului — toate devin fundația pe care se ridică restul.',
          'Poziționarea răspunde la întrebarea esențială: de ce ai alege cineva pe tine și nu pe altul? Răspunsul devine firul roșu al fiecărui material.',
          'Rezultatul: o direcție argumentată, nu o impresie. Fiecare decizie vizuală are un „de ce” pe care îl poți explica oricui.',
        ],
        footnote: 'Claritate · poziționare · direcție',
      },
    },
    {
      id: 'identitate',
      index: 'II',
      label: 'Identitate',
      script: 'ESENȚĂ',
      title: 'O identitate care se recunoaște dintr-o mie',
      summary:
        'Logo, paletă, fonturi și reguli scrise — un sistem vizual pe care îl poți aplica singură, oricând, pe orice platformă.',
      coordinates: 'Scena 02 · Recognoscibilitate',
      image: { src: '/editorial-media/chapter-identitate-tablet.png', alt: 'Femeie în veșmânt auriu citind pe o tabletă luminoasă lângă o fereastră, cu flori de magnolie pe pervaz', position: '72% 35%' },
      detail: {
        kicker: 'Capitolul II · Identitate',
        title: 'Chipul care rămâne în memorie.',
        intro: 'Identitatea vizuală nu e o haină pe care o schimbi după sezon. E chipul brandului — sculptat o dată, bine.',
        quote: 'Culoarea asta, fontul ăsta, ritmul ăsta — fiecare ales pentru că spune ceva despre tine.',
        quoteAttribution: 'Ghid de identitate · principiul 1',
        paragraphs: [
          'Logo-ul profesional vine cu variante cromatice, reguli de folosire și o paletă care ține pe ecran și pe hârtie. Nimic decorativ, totul intenționat.',
          'Primești reguli scrise, nu doar fișiere: cum se folosește fiecare element, cât spațiu respiră, ce combinații sunt interzise.',
          'Așa arată o imagine coerentă pe toate platformele — de la cartea de vizită la feed, fiecare material se recunoaște ca parte din același brand.',
        ],
        footnote: 'Sistem vizual · reguli scrise',
      },
    },
    {
      id: 'design',
      index: 'III',
      label: 'Design',
      script: 'FORMĂ',
      title: 'Forma urmează emoția, nu trendul',
      summary:
        'Proiecte care nu doar arată bine — spun ceva. Storytelling vizual construit pe ce te diferențiază, nu pe ce e la modă.',
      coordinates: 'Scena 03 · Atelierul',
      image: { src: '/editorial-media/chapter-design-tablet.png', alt: 'Femeie în veșmânt roșu-închis citind pe o tabletă luminoasă lângă o fereastră, cu flori de magnolie pe pervaz', position: '72% 35%' },
      detail: {
        kicker: 'Capitolul III · Design',
        title: 'Atelierul unde ideile iau formă.',
        intro: 'În atelier, marmura ideii tale întâlnește daltă cu daltă: materiale grafice, vizualuri, documente și prezentări.',
        quote: 'Un material bun nu se termină la trimiterea fișierului. Începe acolo.',
        quoteAttribution: 'Notițe din atelier',
        paragraphs: [
          'Fiecare vizual e construit cu atenție la detalii: ierarhie clară, spațiu care respiră, tipografie care poartă mesajul fără să strige.',
          'De la mini kit-uri social media la broșuri și rapoarte, toate materialele se leagă între ele când le pui unul lângă altul.',
          'Trendurile trec. Efemerul le ține de mână, dar nu le urmează orbește — direcția vizuală rămâne a ta, nu a algoritmului.',
        ],
        footnote: 'Storytelling vizual · atenție la detalii',
      },
    },
    {
      id: 'experiente',
      index: 'IV',
      label: 'Experiențe digitale',
      script: 'VIITOR',
      title: 'Website-uri care se simt ca viitorul, nu ca template-ul',
      summary:
        'Platforme rapide, elegante și construite pentru conversie — de la structură UX la animații cinematice și elemente 3D.',
      coordinates: 'Scena 04 · Arhitectura',
      image: { src: '/editorial-media/chapter-experiente-inventor.png', alt: 'Tânăr întins pe nori, lucrând pe un laptop futurist, cu ruine grecești clasice în fundal', position: '65% 40%' },
      detail: {
        kicker: 'Capitolul IV · Experiențe digitale',
        title: 'Arhitectura unei prezențe online.',
        intro: 'Un site elegant, rapid și construit pentru conversie e coloana vertebrală a încrederii online.',
        quote: 'Experiența memorabilă nu e ornament. E diferența dintre un vizitator și un client.',
        quoteAttribution: 'Manual de arhitectură digitală',
        paragraphs: [
          'Structură UX gândită pe parcursul vizitatorului: CTA-uri clare, formular, WhatsApp și conținut care răspunde întrebărilor înainte să fie puse.',
          'Responsive pe mobil, SEO de bază și instruire video — preiei site-ul și îl conduci singură, fără frica de butoane necunoscute.',
          'Pentru brandurile care vor mai mult: animații GSAP, storytelling vizual, elemente 3D și conținut — o experiență cinematică, nu o pagină.',
        ],
        footnote: 'Conversie · viteză · cinematica web',
      },
    },
  ],
  landscape: {
    kicker: 'Capitolul 3 · Harta direcțiilor',
    title: 'Atlasul brandului',
    intro:
      'Un brand nu e un punct pe hartă, ci un teritoriu. Trei direcții îl alcătuiesc — identitatea care te face recognoscibil, web-ul care te face credibil și marketingul care te face vizibil. Alege direcția care te reprezintă.',
    folio: 'ATLAS · 003',
    image: {
      src: '/editorial-media/atlas-columns.png',
      alt: 'Hartă-arhitectură de coloane renascentiste scanate de o rețea holografică aurie și cyan',
      position: '50% 50%',
    },
    markers: [
      { id: 'branding', label: 'Branding', text: 'Identități vizuale, logo-uri, direcții cromatice și materiale care fac o afacere recognoscibilă.', x: 13, y: 22, align: 'start' },
      { id: 'web', label: 'Web', text: 'Website-uri și experiențe digitale create pentru prezentare, conversie și încredere.', x: 48, y: 68, align: 'start' },
      { id: 'marketing', label: 'Marketing', text: 'Campanii, conținut vizual și materiale promoționale construite pentru vizibilitate.', x: 80, y: 24, align: 'end' },
    ],
    axisLabels: ['Trecut · Renaștere', 'Prezent · Efemer', 'Viitor · Digital'],
  },
  specimen: {
    kicker: 'Capitolul 4 · Diferența',
    title: 'Un livrabil se termină. Un sistem rămâne.',
    period: 'Metoda Aura’s Digital Dream',
    material: 'Marmură · pixel · lumină',
    summary:
      'Cei mai mulți îți trimit fișierele și dispar. Eu îți las în urmă o structură pe care o poți folosi și fără mine — și peste șase luni, când apare materialul la care nimeni nu se gândise.',
    image: {
      src: '/editorial-media/specimen-bust.png',
      alt: 'Bust renascentist de marmură cu fisuri aurii kintsugi și vizor futurist holografic, petale plutind în jur',
      position: '50% 42%',
    },
    notes: [
      {
        id: 'livrabil',
        heading: 'De obicei primești',
        text: 'Un livrabil. Atât. Un logo trimis pe email fără explicații, culori alese pentru că arătau bine în ziua aceea, un site care seamănă cu alte zece mii și materiale care nu se leagă între ele.',
      },
      {
        id: 'sistem',
        heading: 'De la mine primești',
        text: 'Un sistem care ține: o direcție argumentată, reguli scrise pe care le aplici singură oricând, storytelling construit pe ce te diferențiază și materiale care se recunosc ca parte din același brand.',
      },
    ],
    scaleLabels: ['RENAȘTERE', 'EFEMER', 'FUTUR'],
  },
  records: {
    kicker: 'Capitolul 5 · Dosare de servicii',
    title: 'Nu livrez doar servicii. Creez transformări.',
    intro:
      'Sub un singur acoperiș stă tot ce dă viață unei prezențe: identitate, strategie, design, experiență. Șase dosare, fiecare cu conținut clar, beneficii concrete și buget transparent — prețul final se stabilește după o discuție personalizată.',
    primaryImage: {
      src: '/editorial-media/chapter-atelier.png',
      alt: 'Atelier renascentist cu holograme de proiectare, fundal pentru dosarele de servicii',
      position: '50% 50%',
    },
    detailImage: {
      src: '/editorial-media/atlas-columns.png',
      alt: 'Coloane clasice și rețea holografică, imagine de detaliu pentru dosare',
      position: '50% 45%',
    },
    specimenImage: {
      src: '/editorial-media/specimen-bust.png',
      alt: 'Bust de marmură cu vizor futurist, imagine de studiu pentru dosare',
      position: '50% 38%',
    },
    entries: [
      {
        id: 'pachet-startup',
        index: 'I',
        season: 'Branding',
        date: '900 – 1.200 RON',
        title: 'Pachet Start-up · Identitate completă pentru afaceri noi',
        text: 'Pentru branduri la început, care au nevoie de o imagine clară și credibilă din prima zi.',
        detail: {
          phenology: 'Arăți profesionist din prima zi, ai o imagine coerentă pe toate platformele și materiale gata de folosit.',
          noteHeading: 'Ce primești',
          note: 'Identitatea de bază care ține un brand nou departe de improvizație: logo profesional cu 2 variante cromatice, paletă și fonturi, carte de vizită sau semnătură digitală, mini kit social media (3 postări + 3 stories) și ghid de identitate PDF.',
          findings: [
            { label: 'Logo profesional', text: 'Concept principal + 2 variante cromatice, cu reguli de folosire.' },
            { label: 'Kit vizual', text: 'Paletă cromatică, fonturi și mini kit social media gata de postat.' },
            { label: 'Ghid de identitate', text: 'PDF clar, ca să aplici singură sistemul oriunde.' },
          ],
          facts: [
            { label: 'Investiție', value: '900 – 1.200 RON' },
            { label: 'Ideal pentru', value: 'Branduri la început' },
            { label: 'Livrabile', value: 'Logo, kit, ghid PDF' },
            { label: 'Durata tipică', value: '5–7 zile lucrătoare' },
          ],
        },
      },
      {
        id: 'pachet-rebranding',
        index: 'II',
        season: 'Branding',
        date: '1.500 – 2.200 RON',
        title: 'Pachet Rebranding · Upgrade complet de imagine',
        text: 'Pentru afaceri care există deja, dar au nevoie de o identitate matură și premium.',
        detail: {
          phenology: 'Imagine modernă și coerentă, mai multă încredere și profesionalism, materiale actualizate pentru toate platformele.',
          noteHeading: 'Ce primești',
          note: 'Un reset complet, nu o retușare: audit vizual complet, refresh de logo și direcție vizuală nouă, materiale grafice actualizate, direcție de comunicare, 6 vizualuri social media și ghid de brand PDF.',
          findings: [
            { label: 'Audit vizual', text: 'Analiză onestă a ce funcționează și ce ține brandul pe loc.' },
            { label: 'Refresh de logo', text: 'Direcție vizuală matură, cu materiale grafice actualizate.' },
            { label: 'Direcție de comunicare', text: 'Ton, mesaje și 6 vizualuri social media de pornire.' },
          ],
          facts: [
            { label: 'Investiție', value: '1.500 – 2.200 RON' },
            { label: 'Ideal pentru', value: 'Afaceri existente' },
            { label: 'Livrabile', value: 'Audit, refresh, ghid' },
            { label: 'Durata tipică', value: '1–2 săptămâni' },
          ],
        },
      },
      {
        id: 'pachet-website',
        index: 'III',
        season: 'Web',
        date: '2.000 – 2.500 RON',
        title: 'Pachet Website · Prezență digitală profesionistă',
        text: 'Pentru branduri care vor un site elegant, rapid și construit pentru conversie.',
        detail: {
          phenology: 'Site rapid și modern, mai multă încredere din partea clienților și structură optimizată pentru conversie.',
          noteHeading: 'Ce primești',
          note: 'Website de 5–8 pagini cu structură UX și texte incluse, formular + WhatsApp + CTA-uri, responsive pe mobil, SEO de bază și instruire video ca să-l administrezi singură.',
          findings: [
            { label: '5–8 pagini', text: 'Structură UX și texte gândite pe parcursul vizitatorului.' },
            { label: 'Conversie', text: 'Formular, WhatsApp și CTA-uri clare pe fiecare pagină.' },
            { label: 'Autonomie', text: 'SEO de bază și instruire video pentru administrare.' },
          ],
          facts: [
            { label: 'Investiție', value: '2.000 – 2.500 RON' },
            { label: 'Ideal pentru', value: 'Prezență online serioasă' },
            { label: 'Livrabile', value: 'Site, SEO, instruire' },
            { label: 'Durata tipică', value: '2–3 săptămâni' },
          ],
        },
      },
      {
        id: 'pachet-website-premium',
        index: 'IV',
        season: 'Web',
        date: '3.500 – 4.500 RON',
        title: 'Pachet Website Premium · Storytelling & animații',
        text: 'Pentru branduri care vor o experiență digitală cinematică, nu o pagină.',
        detail: {
          phenology: 'Experiență memorabilă, diferențiere premium și mai mult timp petrecut de vizitatori pe site.',
          noteHeading: 'Ce primești',
          note: 'Design avansat cu animații GSAP / Lottie, storytelling vizual, elemente 3D sau video, strategie de conținut și SEO extins — un site care se simt ca viitorul.',
          findings: [
            { label: 'Animații GSAP / Lottie', text: 'Mișcare care ghidează privirea, nu o obosește.' },
            { label: 'Storytelling vizual', text: 'Parcurs narativ cu elemente 3D și video.' },
            { label: 'Strategie de conținut', text: 'SEO extins și conținut gândit pe termen lung.' },
          ],
          facts: [
            { label: 'Investiție', value: '3.500 – 4.500 RON' },
            { label: 'Ideal pentru', value: 'Branduri premium' },
            { label: 'Livrabile', value: 'Site cinematic, strategie' },
            { label: 'Durata tipică', value: '3–5 săptămâni' },
          ],
        },
      },
      {
        id: 'pachet-social-media',
        index: 'V',
        season: 'Marketing',
        date: '450 – 600 RON / lună',
        title: 'Pachet Social Media · Vizibilitate constantă',
        text: 'Pentru branduri care au nevoie de conținut coerent și o prezență recognoscibilă.',
        detail: {
          phenology: 'Postări coerente vizual, mai multă claritate în comunicare și prezență constantă, fără haos.',
          noteHeading: 'Ce primești',
          note: 'Ritmul constant care ține brandul viu: 6 vizualuri pe lună, template-uri reutilizabile, calendar de conținut, copywriting și o mini strategie care aliniază totul.',
          findings: [
            { label: '6 vizualuri / lună', text: 'Conținut coerent, pe template-uri reutilizabile.' },
            { label: 'Calendar de conținut', text: 'Știi din timp ce se postează și de ce.' },
            { label: 'Copywriting + strategie', text: 'Mesaje clare, nu legende puse la întâmplare.' },
          ],
          facts: [
            { label: 'Investiție', value: '450 – 600 RON / lună' },
            { label: 'Ideal pentru', value: 'Vizibilitate constantă' },
            { label: 'Livrabile', value: 'Vizualuri, calendar, copy' },
            { label: 'Durata tipică', value: 'Abonament lunar' },
          ],
        },
      },
      {
        id: 'pachet-documente',
        index: 'VI',
        season: 'Marketing',
        date: '40 – 60 RON / pagină',
        title: 'Pachet Documente Profesionale · Materiale impecabile',
        text: 'Pentru documente, prezentări și materiale oficiale care trebuie să arate ordonat și profesionist.',
        detail: {
          phenology: 'Documente curate și ușor de citit, imagine serioasă și structură clară pentru informații complexe.',
          noteHeading: 'Ce primești',
          note: 'Prezentări, rapoarte, broșuri și PDF-uri cu tehnoredactare completă — informația complexă devine lizibilă, iar imaginea ta rămâne impecabilă în fața oricărui partener.',
          findings: [
            { label: 'Prezentări & rapoarte', text: 'Structură clară, ierarhie vizuală, zero aglomerare.' },
            { label: 'Broșuri & PDF-uri', text: 'Materiale oficiale gata de print sau trimitere.' },
            { label: 'Tehnoredactare', text: 'Detalii curate până la ultima virgulă.' },
          ],
          facts: [
            { label: 'Investiție', value: '40 – 60 RON / pagină' },
            { label: 'Ideal pentru', value: 'Materiale oficiale' },
            { label: 'Livrabile', value: 'Documente finale, print-ready' },
            { label: 'Durata tipică', value: 'Câteva zile' },
          ],
        },
      },
    ],
  },
  colophon: {
    kicker: 'Final de volum · Spațiul alb',
    quote: 'Apari în lumină. Rămâi în memorie.',
    note: 'Aura Dobre · fondator Aura’s Digital Dream. Începem cu o discuție scurtă despre obiectiv, buget și urgență — restul îl sculptăm împreună.',
    restartLabel: 'Înapoi la începutul visului',
  },
  copy: {
    skipToContent: 'Sari la conținutul principal',
    primaryNavLabel: 'Navigare pe capitole',
    chapterNavLabel: 'Capitolele visului',
    chapterIndexKicker: 'INDEX · MANIFEST',
    archiveFolio: 'ARHIVĂ · 001 / 006',
    footerCredit: 'AURA’S DIGITAL DREAM · MMXXVI',
    openChapter: 'Vezi capitolul',
    activeChapter: 'Capitol curent',
    imageUnavailable: 'Imaginea nu este disponibilă încă',
    scrollProgress: 'Progres de lectură',
    returnToTop: 'Înapoi la început',
    openChapterDetail: 'Deschide capitolul',
    openRecordDetail: 'Citește dosarul',
    closeDetail: 'Închide pagina',
    chapterDetailBack: 'Înapoi la manifest',
    recordDetailBack: 'Înapoi la dosare',
    nextChapter: 'Capitolul următor',
    nextRecord: 'Dosarul următor',
    detailMissing: 'Pagina nu există — sau s-a întors în arhivă.',
  },
  motion: {
    reveals: true,
    imageDrift: true,
    paperBreath: true,
    scrollCue: true,
  },
}

